name: Run Puppeteer Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Puppeteer script
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: false
          PUPPETEER_EXECUTABLE_PATH: ""
        run: |
          node -e "
          (async () => {
            const puppeteer = require('puppeteer');
            const browser = await puppeteer.launch({
              headless: 'new',
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.goto('https://example.com', { waitUntil: 'networkidle2' });
            console.log(await page.title());
            await browser.close();
          })();
          "
