name: Run TFS Search

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libasound2 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            wget

      - name: Run TFS Search
        run: node tfs-search.js
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
          PUPPETEER_DISABLE_HEADLESS_WARNING: "true"
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox"
